# See https://openmod.github.io/openmod-docs/devdoc/concepts/configuration.html
# You can delete this file if you do not need a configuration


Blacklist:
    
#Items you shouln't be able to place while raid is disabled    
  Placing:
    - 1241

#Barricades that can be damaged regardless of raid enabled  
  Barricades:
    - 1091

#Structures that can be damaged regardless of raid enabled  
  Structures:
    - 369